# Site settings
title: Health Care Lab
email: info@healthcarelab.info
description: > # this means to ignore newlines until "baseurl:"
  health care lab.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://healthcarelab.info" # the base hostname & protocol for your site
twitter_username: healthcarelab
github_username:  healthcarelab

# Build settings
markdown: healthcarelab

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
